console.log('pirma dalis' + ' antra dalis')
console.log('==============================')
console.log('pirma ' + 'antra' + ' trecia')
console.log('pirma' , 'antra' , 'trecia')
console.log('pirma' + 'antra' , 'trecia')
console.log('==============================')
